limited_partnerships.mongodb.dbname=transactions_limited_partnerships
spring.mongodb.uri=${MONGODB_URL}/${limited_partnerships.mongodb.dbname}
# Spring actuator end-points config
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoints.web.base-path=/limited-partnership/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=always
# OpenTelemetry configuration
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
