#!/bin/bash

full_path=$(realpath $0)
dir_path=$(dirname $full_path)

jar_file="$dir_path/google-java-format-1.24.0-all-deps.jar"

changed_java_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*java$" || true)

if [[ -n "$changed_java_files" ]]
then
    echo "Reformatting Java files: $changed_java_files"
    if ! java -jar "$jar_file" --replace --set-exit-if-changed $changed_java_files
    then
        git add -f $changed_java_files
        echo -e "\nReformatted and staged!" >&2
    fi
else
    echo "No Java files changes found."
fi
