package uk.gov.companieshouse.limitedpartnershipsapi.model.limitedpartner;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;

public enum Currency {
    AFGHANISTAN("Afghani", "AFN"),
    ALAND_ISLANDS("Euro", "EUR"),
    ALBANIA("Lek", "ALL"),
    ALGERIA("Algerian Dinar", "DZD"),
    ALDERNEY("British Pound", "GBP"),
    AMERICAN_SAMOA("US Dollar", "USD"),
    ANDORRA("Euro", "EUR"),
    ANGOLA("Kwanza", "AOA"),
    ANGUILLA("East Caribbean Dollar", "XCD"),
    ANTARCTICA("No Universal Currency", "N/A"),
    ANTIGUA_AND_BARBUDA("East Caribbean Dollar", "XCD"),
    ARGENTINA("Argentine Peso", "ARS"),
    ARMENIA("Armenian Dram", "AMD"),
    ARUBA("Aruban Florin", "AWG"),
    AUSTRALIA("Australian Dollar", "AUD"),
    AUSTRIA("Euro", "EUR"),
    AZERBAIJAN("Azerbaijani Manat", "AZN"),
    BAHAMAS("Bahamian Dollar", "BSD"),
    BAHRAIN("Bahraini Dinar", "BHD"),
    BANGLADESH("Taka", "BDT"),
    BARBADOS("Barbadian Dollar", "BBD"),
    BELARUS("Belarusian Ruble", "BYN"),
    BELGIUM("Euro", "EUR"),
    BELIZE("Belize Dollar", "BZD"),
    BENIN("West African CFA Franc", "XOF"),
    BERMUDA("Bermudian Dollar", "BMD"),
    BHUTAN("Ngultrum", "BTN"),
    BOLIVIA("Boliviano", "BOB"),
    BONAIRE_SINT_EUSTATIUS_AND_SABA("US Dollar", "USD"),
    BOSNIA_AND_HERZEGOVINA("Convertible Mark", "BAM"),
    BOTSWANA("Pula", "BWP"),
    BOUVET_ISLAND("Norwegian Krone", "NOK"),
    BRAZIL("Brazilian Real", "BRL"),
    BRITISH_INDIAN_OCEAN_TERRITORY("US Dollar", "USD"),
    BRUNEI_DARUSSALAM("Brunei Dollar", "BND"),
    BULGARIA("Bulgarian Lev", "BGN"),
    BURKINA_FASO("West African CFA Franc", "XOF"),
    BURUNDI("Burundian Franc", "BIF"),
    CAMBODIA("Riel", "KHR"),
    CAMEROON("Central African CFA Franc", "XAF"),
    CANADA("Canadian Dollar", "CAD"),
    CAPE_VERDE("Cape Verdean Escudo", "CVE"),
    CAYMAN_ISLANDS("Cayman Islands Dollar", "KYD"),
    CENTRAL_AFRICAN_REPUBLIC("Central African CFA Franc", "XAF"),
    CHAD("Central African CFA Franc", "XAF"),
    CHILE("Chilean Peso", "CLP"),
    CHINA("Yuan Renminbi", "CNY"),
    CHRISTMAS_ISLAND("Australian Dollar", "AUD"),
    COCOS_KEELING_ISLANDS("Australian Dollar", "AUD"),
    COLOMBIA("Colombian Peso", "COP"),
    COMOROS("Comorian Franc", "KMF"),
    CONGO("Central African CFA Franc", "XAF"),
    CONGO_DEMOCRATIC_REPUBLIC("Congolese Franc", "CDF"),
    COOK_ISLANDS("New Zealand Dollar", "NZD"),
    COSTA_RICA("Costa Rican Colon", "CRC"),
    CROATIA("Euro", "EUR"),
    CUBA("Cuban Peso", "CUP"),
    CURACAO("Netherlands Antillean Guilder", "ANG"),
    CYPRUS("Euro", "EUR"),
    CZECH_REPUBLIC("Czech Koruna", "CZK"),
    DENMARK("Danish Krone", "DKK"),
    DJIBOUTI("Djiboutian Franc", "DJF"),
    DOMINICA("East Caribbean Dollar", "XCD"),
    DOMINICAN_REPUBLIC("Dominican Peso", "DOP"),
    EAST_TIMOR("US Dollar", "USD"),
    ECUADOR("US Dollar", "USD"),
    EGYPT("Egyptian Pound", "EGP"),
    EL_SALVADOR("US Dollar", "USD"),
    ENGLAND("British Pound", "GBP"),
    EQUATORIAL_GUINEA("Central African CFA Franc", "XAF"),
    ERITREA("Nakfa", "ERN"),
    ESTONIA("Euro", "EUR"),
    ESWATINI("Lilangeni", "SZL"),
    ETHIOPIA("Ethiopian Birr", "ETB"),
    FALKLAND_ISLANDS("Falkland Islands Pound", "FKP"),
    FAROE_ISLANDS("Danish Krone", "DKK"),
    FIJI("Fijian Dollar", "FJD"),
    FINLAND("Euro", "EUR"),
    FRANCE("Euro", "EUR"),
    FRENCH_GUIANA("Euro", "EUR"),
    FRENCH_POLYNESIA("CFP Franc", "XPF"),
    FRENCH_SOUTHERN_TERRITORIES("Euro", "EUR"),
    GABON("Central African CFA Franc", "XAF"),
    GAMBIA("Dalasi", "GMD"),
    GEORGIA("Lari", "GEL"),
    GERMANY("Euro", "EUR"),
    GHANA("Ghanaian Cedi", "GHS"),
    GIBRALTAR("Gibraltar Pound", "GIP"),
    GREECE("Euro", "EUR"),
    GREENLAND("Danish Krone", "DKK"),
    GRENADA("East Caribbean Dollar", "XCD"),
    GUADELOUPE("Euro", "EUR"),
    GUAM("US Dollar", "USD"),
    GUATEMALA("Quetzal", "GTQ"),
    GUERNSEY("British Pound", "GBP"),
    GUINEA("Guinean Franc", "GNF"),
    GUINEA_BISSAU("West African CFA Franc", "XOF"),
    GUYANA("Guyanese Dollar", "GYD"),
    HAITI("Gourde", "HTG"),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS("Australian Dollar", "AUD"),
    HERM("British Pound", "GBP"),
    HONDURAS("Lempira", "HNL"),
    HONG_KONG("Hong Kong Dollar", "HKD"),
    HUNGARY("Forint", "HUF"),
    ICELAND("Icelandic Krona", "ISK"),
    INDIA("Indian Rupee", "INR"),
    INDONESIA("Rupiah", "IDR"),
    IRAN("Iranian Rial", "IRR"),
    IRAQ("Iraqi Dinar", "IQD"),
    IRELAND("Euro", "EUR"),
    ISLE_OF_MAN("British Pound", "GBP"),
    ISRAEL("Israeli New Shekel", "ILS"),
    ITALY("Euro", "EUR"),
    IVORY_COAST("West African CFA Franc", "XOF"),
    JAMAICA("Jamaican Dollar", "JMD"),
    JAPAN("Yen", "JPY"),
    JERSEY("British Pound", "GBP"),
    JORDAN("Jordanian Dinar", "JOD"),
    KAZAKHSTAN("Tenge", "KZT"),
    KENYA("Kenyan Shilling", "KES"),
    KIRIBATI("Australian Dollar", "AUD"),
    KOSOVO("Euro", "EUR"),
    KUWAIT("Kuwaiti Dinar", "KWD"),
    KYRGYZSTAN("Som", "KGS"),
    LAOS("Kip", "LAK"),
    LATVIA("Euro", "EUR"),
    LEBANON("Lebanese Pound", "LBP"),
    LESOTHO("Loti", "LSL"),
    LIBERIA("Liberian Dollar", "LRD"),
    LIBYA("Libyan Dinar", "LYD"),
    LIECHTENSTEIN("Swiss Franc", "CHF"),
    LITHUANIA("Euro", "EUR"),
    LUXEMBOURG("Euro", "EUR"),
    MACAO("Pataca", "MOP"),
    MADAGASCAR("Malagasy Ariary", "MGA"),
    MALAWI("Malawian Kwacha", "MWK"),
    MALAYSIA("Malaysian Ringgit", "MYR"),
    MALDIVES("Rufiyaa", "MVR"),
    MALI("West African CFA Franc", "XOF"),
    MALTA("Euro", "EUR"),
    MARSHALL_ISLANDS("US Dollar", "USD"),
    MARTINIQUE("Euro", "EUR"),
    MAURITANIA("Ouguiya", "MRU"),
    MAURITIUS("Mauritian Rupee", "MUR"),
    MAYOTTE("Euro", "EUR"),
    MEXICO("Mexican Peso", "MXN"),
    MICRONESIA("US Dollar", "USD"),
    MOLDOVA("Moldovan Leu", "MDL"),
    MONACO("Euro", "EUR"),
    MONGOLIA("Tugrik", "MNT"),
    MONTENEGRO("Euro", "EUR"),
    MONTSERRAT("East Caribbean Dollar", "XCD"),
    MOROCCO("Moroccan Dirham", "MAD"),
    MOZAMBIQUE("Mozambican Metical", "MZN"),
    MYANMAR("Kyat", "MMK"),
    NAMIBIA("Namibian Dollar", "NAD"),
    NAURU("Australian Dollar", "AUD"),
    NEPAL("Nepalese Rupee", "NPR"),
    NETHERLANDS("Euro", "EUR"),
    NEW_CALEDONIA("CFP Franc", "XPF"),
    NEW_ZEALAND("New Zealand Dollar", "NZD"),
    NICARAGUA("Cordoba", "NIO"),
    NIGER("West African CFA Franc", "XOF"),
    NIGERIA("Naira", "NGN"),
    NIUE("New Zealand Dollar", "NZD"),
    NORFOLK_ISLAND("Australian Dollar", "AUD"),
    NORTH_KOREA("North Korean Won", "KPW"),
    NORTHERN_IRELAND("British Pound", "GBP"),
    NORTHERN_MARIANA_ISLANDS("US Dollar", "USD"),
    NORWAY("Norwegian Krone", "NOK"),
    OMAN("Rial", "OMR"),
    PAKISTAN("Pakistani Rupee", "PKR"),
    PALAU("US Dollar", "USD"),
    PALESTINE_STATE_OF("Israeli New Shekel", "ILS"),
    PANAMA("Balboa", "PAB"),
    PAPUA_NEW_GUINEA("Kina", "PGK"),
    PARAGUAY("Guarani", "PYG"),
    PERU("Sol", "PEN"),
    PHILIPPINES("Philippine Peso", "PHP"),
    PITCAIRN("New Zealand Dollar", "NZD"),
    POLAND("Zloty", "PLN"),
    PORTUGAL("Euro", "EUR"),
    PUERTO_RICO("US Dollar", "USD"),
    QATAR("Qatari Rial", "QAR"),
    REUNION("Euro", "EUR"),
    ROMANIA("Romanian Leu", "RON"),
    RUSSIA("Russian Ruble", "RUB"),
    RWANDA("Rwandan Franc", "RWF"),
    SAINT_BARTHELEMY("Euro", "EUR"),
    SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA("Saint Helena Pound", "SHP"),
    SAINT_KITTS_AND_NEVIS("East Caribbean Dollar", "XCD"),
    SAINT_LUCIA("East Caribbean Dollar", "XCD"),
    SAINT_MARTIN_FRENCH_PART("Euro", "EUR"),
    SAINT_PIERRE_AND_MIQUELON("Euro", "EUR"),
    SAINT_VINCENT_AND_THE_GRENADINES("East Caribbean Dollar", "XCD"),
    SAMOA("Tala", "WST"),
    SAN_MARINO("Euro", "EUR"),
    SAO_TOME_AND_PRINCIPE("Dobra", "STN"),
    SARK("British Pound", "GBP"),
    SAUDI_ARABIA("Saudi Riyal", "SAR"),
    SCOTLAND("British Pound", "GBP"),
    SENEGAL("West African CFA Franc", "XOF"),
    SERBIA("Serbian Dinar", "RSD"),
    SEYCHELLES("Seychellois Rupee", "SCR"),
    SIERRA_LEONE("Leone", "SLL"),
    SINGAPORE("Singapore Dollar", "SGD"),
    SINT_MAARTEN_DUTCH_PART("Netherlands Antillean Guilder", "ANG"),
    SLOVAKIA("Euro", "EUR"),
    SLOVENIA("Euro", "EUR"),
    SOLOMON_ISLANDS("Solomon Islands Dollar", "SBD"),
    SOMALIA("Somali Shilling", "SOS"),
    SOUTH_AFRICA("Rand", "ZAR"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("No Universal Currency", "N/A"),
    SOUTH_KOREA("South Korean Won", "KRW"),
    SOUTH_SUDAN("South Sudanese Pound", "SSP"),
    SPAIN("Euro", "EUR"),
    SRI_LANKA("Sri Lankan Rupee", "LKR"),
    SUDAN("Sudanese Pound", "SDG"),
    SURINAME("Surinamese Dollar", "SRD"),
    SVALBARD_AND_JAN_MAYEN("Norwegian Krone", "NOK"),
    SWEDEN("Swedish Krona", "SEK"),
    SWITZERLAND("Swiss Franc", "CHF"),
    SYRIA("Syrian Pound", "SYP"),
    TAIWAN("New Taiwan Dollar", "TWD"),
    TAJIKISTAN("Somoni", "TJS"),
    TANZANIA("Tanzanian Shilling", "TZS"),
    THAILAND("Baht", "THB"),
    TOGO("West African CFA Franc", "XOF"),
    TOKELAU("New Zealand Dollar", "NZD"),
    TONGA("Paʻanga", "TOP"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago Dollar", "TTD"),
    TUNISIA("Tunisian Dinar", "TND"),
    TURKEY("Turkish Lira", "TRY"),
    TURKMENISTAN("Manat", "TMT"),
    TURKS_AND_CAICOS_ISLANDS("US Dollar", "USD"),
    TUVALU("Australian Dollar", "AUD"),
    UGANDA("Ugandan Shilling", "UGX"),
    UKRAINE("Hryvnia", "UAH"),
    UNITED_ARAB_EMIRATES("Dirham", "AED"),
    UNITED_KINGDOM("British Pound", "GBP"),
    UNITED_STATES("US Dollar", "USD"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("US Dollar", "USD"),
    URUGUAY("Peso", "UYU"),
    UZBEKISTAN("Som", "UZS"),
    VANUATU("Vatu", "VUV"),
    VATICAN_CITY("Euro", "EUR"),
    VENEZUELA("Bolivar", "VES"),
    VIETNAM("Dong", "VND"),
    VIRGIN_ISLANDS_BRITISH("US Dollar", "USD"),
    VIRGIN_ISLANDS_US("US Dollar", "USD"),
    WALES("British Pound", "GBP"),
    WALLIS_AND_FUTUNA("CFP Franc", "XPF"),
    WESTERN_SAHARA("Moroccan Dirham", "MAD"),
    YEMEN("Yemeni Rial", "YER"),
    ZAMBIA("Zambian Kwacha", "ZMW"),
    ZIMBABWE("Zimbabwean Dollar", "ZWL"),

    @JsonEnumDefaultValue
    UNKNOWN("Unknown Currency", "N/A");

    private final String description;
    private final String code;

    Currency(String description, String code) {
        this.description = description;
        this.code = code;
    }

    @JsonCreator
    public static Currency fromDescription(String description) {
        for (Currency currency : Currency.values()) {
            if (currency.getDescription().equalsIgnoreCase(description)) {
                return currency;
            }
        }
        return Currency.UNKNOWN;
    }

    public String getDescription() {
        return description;
    }

    public String getCode() {
        return code;
    }
}